### ISSUE TITLE
Local File System

### ISSUE THREAD

**Issue by gamidon** [worldbeater/Camelotia#5]
Current output of Local file system that is displayed on the interface is confusing.  The initial view of the file system should be of the Drives, then when drilling down through the drives the drive content should then be displayed.   If there is only one drive then the root contents of that drive should be shown.  This would allow removable devices to be displayed if present as well.

 The current implementation starts with:

`            _refresh = ReactiveCommand.CreateFromTask(
                () => provider.Get(CurrentPath),
                outputScheduler: mainThread);
`
CurrentPath is null at start and when Get is called on the local provider it passes in "\\"  So the view output consists entirely of the drive that the app is run from. This excludes other drives.

I suggest that if the initial path is null, we convert that to get the drives and display those.  Then when drilling down it can be from any drive.  We can also look at allowing a CD/DVD drive if it is available and not exclude it entirely like I did to get rid of the exception.  When I implemented that there was no way to view the drive anyway so excluding it to avoid the exception seemed like a valid solution.  

This suggestion is entirely contained in the local system provider as I am not sure if the other providers would have a concept of multiple drives, and if they did the implementation would be different anyway.

Let me know if you would like this and I will provide and implementation to it that you can review. 
Greg

**Comment by worldbeater** [comment]
Good day @gamidon and thank you for your contribution. 

I agree the issue you describe exists and should be resolved. I think introducing a new `IProvider.InitialPath` property could be a better option, with such property we could let the providers decide where to begin displaying files on their own. 

Then, for most cloud file storages the `IProvider.InitialPath` property should be `/` and for local file storage it'll be something like `drives` or `my-computer` or something like that (using `null`s as valid values generally doesn't seem to be a good idea, and [here is explained why](https://www.yegor256.com/2014/05/13/why-null-is-bad.html)).

**Comment by gamidon** [comment]
About the null.  I was referring to the fact that on startup: 
`public string CurrentPath => _currentPath?.Value;`  is uninitialized and in fact null. 
You already are managing around this null.  If you remove the Elvis operator from this:
`public string CurrentPath => _currentPath?.Value;` an exception will be thrown. 

I am not a fan of the FodyWeavers for this because I cannot easily determine or breakpoint when a field is set.  So reading code to find the actual set is more time consuming and if I wanted to break on all set calls I have to find all the places it might actually be set.  So if a field changed unexpectedly somewhere in the code trapping that is made more difficult.  I think using set with RaiseAndSetIfChanged is one additional line per field that is worth it.  You can always make it a private set and get the same data security as Fody.  Fody just changes a private set with a reflection set and does not prohibit multiple calls in the viewmodel from stepping on each other.  The fody way removes the one path to set and created multiple paths to set.  Just a personal preference....  Everyone has there own :)  When "Magic" happens its always harder to debug when something goes wrong.

**Comment by worldbeater** [comment]
I see your point, thanks! Worth mentioning that Fody doesn't actually modify those get-only properties. The `ObservableAsPropertyHelper<T>` is a [ReactiveUI feature](https://reactiveui.net/docs/handbook/oaph/), Fody uses code generation only for properties marked with `[Reactive]` attribute. I prefer OAPHs because of their immutability, OAPH properties always reflect latest values that have been sent through an [IObservable](http://reactivex.io/documentation/observable.html) stream. This allows us to describe relations among properties and commands declaratively and "[express the idea around a feature in one readable place](https://github.com/reactiveui/reactiveUI/)", the app won't compile if the developer accidentally tries to mutate a property in a non-reactive manner. Elvis operator is used for `CurrentPath` property because that property is [used inside a `WhenAny` call](https://github.com/worldbeater/Camelotia/blob/master/Camelotia.Presentation/ViewModels/ProviderViewModel.cs#L76) before [the `CurrentPath` property is initialized](https://github.com/worldbeater/Camelotia/blob/master/Camelotia.Presentation/ViewModels/ProviderViewModel.cs#L86), I can admit it's kind of a hack to avoid dealing with mutable state where it is not entirely neccessary. :) So I agree that sometimes using nulls is a necessary evil, but if there is a chance to avoid that, it's worth trying.

**Comment by gamidon** [comment]
I implemented the feature, it works fine, but now I have to use the null coalescing operator on
`            _open = ReactiveCommand.Create(
                () => Path.Combine(CurrentPath ?? _provider.InitialPath, SelectedFile.Name), 
                canOpenCurrentPath, mainThread);
`
This is due to retracing _back.  Eventually you can return to the null value.  I don't know how to set a value to CurrentPath that initializes it from the constructor and never lets it be null.  If there is a way please let me know how.  If not this is way more work than it is solving as now I am chasing that null it can hit at run time. 

Totally appreciate any idea on how best to solve this, right now it is a really poor way to handle CurrentPath and error prone at run time.  The resulting code is more dangerous than just using a private set since and future changes will not necessarily understand that the value can return to null.  I was surprised when I got hit with it.

I will Pull request soon so you can take a look.
Thanks,
Greg

**Comment by worldbeater** [comment]
@gamidon I think the solution you are looking for is passing the `InitialPath` value to ObservableAsPropertyHelper that controls the `CurrentPath` property. You need to pass the `InitialPath` value as a parameter to a `.ToProperty` call, the parameter name is `initialValue`. An example:
```cs
 _currentPath = pipeline
    .ToProperty(this, x => x.CurrentPath, initialValue: provider.InitialPath); // *
```

**Comment by worldbeater** [comment]
Closing this as resolved by https://github.com/worldbeater/Camelotia/pull/6

Thanks @gamidon :heart: :+1:
